In [2]:
import numpy as np

In [129]:
class platform:
    def __init__(self,d):
        self.c1=d*np.array([0,-d,0])
        self.c2=d*np.array([d*np.sin(np.pi/3),d*np.cos(np.pi/3),0])
        self.c3=d*np.array([-d*np.sin(np.pi/3),d*np.cos(np.pi/3),0])

    def x_y_rotation_matrix (self,r_x,r_y):
        "Esta función toma como parametros los angulos de rotacion en radianes respecto de los ejes x e y"
        "y entrega como resultado una matriz tal que al pre multiplicar un vector por ella se rota al mismo en los"
        "angulos deseado"
        M_x= np.array([[1,0,0],[0,np.cos(r_x),-np.sin(r_x)],[0,np.sin(r_x),np.cos(r_x)]]) 
        M_y= np.array([[np.cos(r_y),0,np.sin(r_y)],[0,1,0],[-np.sin(r_y),0,np.cos(r_y)]])
        return M_x.dot(M_y)
    def rotate(self,r_x,r_y):
        Mxy=self.x_y_rotation_matrix (r_x,r_y)
        self.c1=np.transpose(Mxy.dot(self.c1.transpose()))
        self.c2=np.transpose(Mxy.dot(self.c2.transpose()))
        self.c3=np.transpose(Mxy.dot(self.c3.transpose()))

In [130]:
platform=platform(d=1)

In [131]:
platform.c1

array([ 0, -1,  0])

In [132]:
platform.c2

array([0.8660254, 0.5      , 0.       ])

In [133]:
platform.rotate(np.pi*0.5,0)

In [134]:
platform.c1

array([ 0.000000e+00, -6.123234e-17, -1.000000e+00])

In [135]:
platform.c2

array([8.66025404e-01, 3.06161700e-17, 5.00000000e-01])

In [136]:
platform.c3

array([-8.66025404e-01,  3.06161700e-17,  5.00000000e-01])